name: Mina Docker Image Builder
run-name: Builds Mina Docker image from an arbitrary branch
on:
  workflow_dispatch:
    inputs:
      repository:
        type: string
        required: true
      branch:
        type: string
        required: true
env:
  MINA_REPO: ${{inputs.repository}}
  MINA_BRANCH: ${{inputs.branch}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker

      - name: Build 1
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: build1

      - name: Build 2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile2
          tags: build2

      - name: Checkout Mina
        uses: actions/checkout@v3
        with:
          repository: ${{env.MINA_REPO}}
          ref: ${{env.MINA_BRANCH}}
          path: mina

      - name: Build Deps
        uses: docker/build-push-action@v2
        with:
          context: mina
          file: mina/dockerfiles/stages/1-build-deps
          tags: build-deps

      - name: Opam Deps
        uses: docker/build-push-action@v2
        with:
          context: mina
          file: mina/dockerfiles/stages/2-opam-deps
          tags: opam-deps
          build-args: |
            MINA_REPO=http://github.com/${{env.MINA_REPO}}
            MINA_BRANCH=${{env.MINA_BRANCH}}

      - name: Toolchain
        uses: docker/build-push-action@v2
        with:
          context: mina
          file: mina/dockerfiles/stages/3-toolchain
          tags: toolchain

      - name: Deb Builder
        uses: docker/build-push-action@v2
        with:
          context: mina
          file: mina/dockerfiles/stages/4-deb-builder
          tags: deb-builder
          build-args: |
            MINA_BRANCH=${{env.MINA_BRANCH}}
            MINA_COMMIT=xxx

      - name: Debug
        run: |
          git status
